### ISSUE TITLE
Problem z działaniem + GUI

### ISSUE THREAD

**Issue by yureyone** [norbi002/nDrop#1]
Po uruchomieniu GUI, wyświetla się normalnie - natomiast, przy najechaniu na kopaliwa (Diamenty etc) na miejscu gdzie powinno się wyświetlać włączanie/wyłączanie dropu wyświetla się "kliknij aby <none> wylatywania z kamienia/bruku.

To samo z wyświetlaniem aktualnego statusu on/off - pokazuje się "Dropi ze stone : <none>

W momencie naciśnięcia tych elementów w GUI na chacie skrypt printuje "Drop> <none>

**Comment by norbi002** [comment]
Usuń plik konfiguracyjny i przeładuj skrypt.

**Comment by yureyone** [comment]
To samo. Po dłuższym czasie kombinowania przeskoczyłem jednak na stare i sprawdzone otherdropsy, ale jednak na w razie czego jakby co wiesz że coś może nie stykać :P
